export const chapter = "Chapter - 4: Minerals and Energy Resources";
export const noOfActivities = 3;
export var activityData;

const shuffleQues = (ques) => {
  let arr = ques.slice();
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
};

const shuffleOptions = (object) => {
  const optionKeys = ["optionA", "optionB", "optionC", "optionD"];
  const optionsArray = optionKeys
    .map((key) => object[key])
    .filter((option) => option !== undefined);

  for (let i = optionsArray.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [optionsArray[i], optionsArray[j]] = [
      optionsArray[j],
      optionsArray[i],
    ];
  }

  optionKeys.forEach((key, index) => {
    if (index < optionsArray.length) {
      object[key] = optionsArray[index];
    } else {
      delete object[key];
    }
  });

  return object;
};

if (localStorage.getItem("activityNumber") == 1) {
  activityData = {
    activity: "Tick the correct option:",
    questions: shuffleQues([
      shuffleOptions({
        question: "Which mineral is known for its property of being the hardest natural substance?",
        optionA: "Quartz",
        optionB: "Gypsum",
        optionC: "Diamond",
        correctAnswer: "Diamond",
      }),
      shuffleOptions({
        question: "Which mining method is used when minerals lie close to the earth’s surface?",
        optionA: "Deep shaft mining",
        optionB: "Open-cast mining",
        optionC: "Drilling",
        correctAnswer: "Open-cast mining",
      }),
      shuffleOptions({
        question: "Which country is the world’s leading producer of coal?",
        optionA: "China",
        optionB: "Germany",
        optionC: "South Africa",
        correctAnswer: "China",
      }),
      shuffleOptions({
        question: "Which energy resource is commonly referred to as “liquid gold”?",
        optionA: "Coal",
        optionB: "Petroleum",
        optionC: "Natural gas",
        correctAnswer: "Petroleum",
      }),
      shuffleOptions({
        question: "Which metal is widely used for making electrical wires due to excellent conductivity?",
        optionA: "Lead",
        optionB: "Copper",
        optionC: "Mica",
        correctAnswer: "Copper",
      }),
      shuffleOptions({
        question: "Which coal variety is considered the best quality due to its high carbon content?",
        optionA: "Lignite",
        optionB: "Peat",
        optionC: "Anthracite",
        correctAnswer: "Anthracite",
      }),
      shuffleOptions({
        question: "Which renewable source of energy uses fast-moving air to generate electricity?",
        optionA: "Solar energy",
        optionB: "Wind energy",
        optionC: "Geothermal energy",
        correctAnswer: "Wind energy",
      }),
      shuffleOptions({
        question: "Which country is known as the \"land of hot springs and geysers\" due to rich geothermal activity?",
        optionA: "Iceland",
        optionB: "New Zealand",
        optionC: "Japan",
        correctAnswer: "New Zealand",
      }),
      shuffleOptions({
        question: "Which Indian offshore region is famous for petroleum production?",
        optionA: "Digboi",
        optionB: "Bombay High",
        optionC: "Raniganj",
        correctAnswer: "Bombay High",
      }),
      shuffleOptions({
        question: "Which mineral is the chief ore of aluminium?",
        optionA: "Bauxite",
        optionB: "Hematite",
        optionC: "Magnetite",
        correctAnswer: "Bauxite",
      }),
    ]),
  };
}

if (localStorage.getItem("activityNumber") == 2) {
  activityData = {
    activity: "Fill in the blank with correct option:",
    questions: shuffleQues([
      shuffleOptions({
        question: "Coal formed from ancient decayed vegetation is often called ______ sunshine.",
        optionA: "buried",
        optionB: "hidden",
        optionC: "shining",
        correctAnswer: "buried",
      }),
      shuffleOptions({
        question: "The electricity generated by burning coal is known as ______ power.",
        optionA: "thermal",
        optionB: "hydel",
        optionC: "tidal",
        correctAnswer: "thermal",
      }),
      shuffleOptions({
        question: "Aluminium is preferred over iron because it is light and ______ proof.",
        optionA: "water",
        optionB: "dust",
        optionC: "rust",
        correctAnswer: "rust",
      }),
      shuffleOptions({
        question: "Petroleum is extracted from deep ______ wells.",
        optionA: "coal",
        optionB: "oil",
        optionC: "gas",
        correctAnswer: "oil",
      }),
      shuffleOptions({
        question: "Minerals that contain iron are known as ______ minerals.",
        optionA: "ferrous",
        optionB: "non-metallic",
        optionC: "alloy",
        correctAnswer: "ferrous",
      }),
      shuffleOptions({
        question: "Natural gas is a colourless and highly ______ fuel.",
        optionA: "inflammable",
        optionB: "soluble",
        optionC: "magnetic",
        correctAnswer: "inflammable",
      }),
      shuffleOptions({
        question: "Hydel power is generated using falling ______.",
        optionA: "wind",
        optionB: "sunlight",
        optionC: "water",
        correctAnswer: "water",
      }),
      shuffleOptions({
        question: "The solar energy collected by solar cells is converted directly into ______.",
        optionA: "electricity",
        optionB: "diesel",
        optionC: "heat only",
        correctAnswer: "electricity",
      }),
      shuffleOptions({
        question: "Bauxite is usually found in ______ rocks.",
        optionA: "sedimentary",
        optionB: "igneous",
        optionC: "metamorphic",
        correctAnswer: "sedimentary",
      }),
      shuffleOptions({
        question: "Nuclear power in India mainly uses uranium and ______.",
        optionA: "copper",
        optionB: "mica",
        optionC: "thorium",
        correctAnswer: "thorium",
      }),
    ]),
  };
}

if (localStorage.getItem("activityNumber") == 3) {
  activityData = {
    activity: "Write 'True' for True and 'False' for False statements:",
    questions: shuffleQues([
      shuffleOptions({
        question: "Metallic minerals are good conductors of heat and electricity.",
        optionA: "True",
        optionB: "False",
        correctAnswer: "True",
      }),
      shuffleOptions({
        question: "Lignite is the best quality coal.",
        optionA: "True",
        optionB: "False",
        correctAnswer: "False",
      }),
      shuffleOptions({
        question: "Solar energy is a non-conventional source of power.",
        optionA: "True",
        optionB: "False",
        correctAnswer: "True",
      }),
      shuffleOptions({
        question: "Petroleum is formed in the layers of sedimentary rocks.",
        optionA: "True",
        optionB: "False",
        correctAnswer: "True",
      }),
      shuffleOptions({
        question: "Natural gas emits more carbon dioxide than coal.",
        optionA: "True",
        optionB: "False",
        correctAnswer: "False",
      }),
      shuffleOptions({
        question: "Bauxite is the main ore of aluminium.",
        optionA: "True",
        optionB: "False",
        correctAnswer: "True",
      }),
      shuffleOptions({
        question: "Windmills generate electricity when high-speed winds rotate their blades.",
        optionA: "True",
        optionB: "False",
        correctAnswer: "True",
      }),
      shuffleOptions({
        question: "Geothermal energy comes from the heat inside the earth.",
        optionA: "True",
        optionB: "False",
        correctAnswer: "True",
      }),
      shuffleOptions({
        question: "Copper is a poor conductor of electricity.",
        optionA: "True",
        optionB: "False",
        correctAnswer: "False",
      }),
      shuffleOptions({
        question: "Hydel power plants are usually located on dams.",
        optionA: "True",
        optionB: "False",
        correctAnswer: "True",
      }),
    ]),
  };
}
