export const chapter = "Chapter - 14: The Earth's Interior  ";
export const noOfActivities = 3;

if (localStorage.getItem("activityNumber") == 1) {
  activityData = {
    activity: "Tick the correct option:",
    questions: [
      {
        question: "What is the outermost layer of the Earth called?",
        optionA: "Mantle",
        optionB: "Crust",
        optionC: "Core",
        correctAnswer: "b",
      },
      {
        question:
          "What is the average temperature range of the Earth's mantle?",
        optionA: "0°C to 100°C",
        optionB: "900°C to 2,000°C",
        optionC: "2,200°C to 5,000°C",
        correctAnswer: "b",
      },
      {
        question: "What are seismic waves, and how are they generated?",
        optionA: "Ocean currents, generated by tides",
        optionB: "Earthquakes, generated at the epicentre",
        optionC: "Winds, generated by atmospheric pressure",
        correctAnswer: "b",
      },
      {
        question:
          "Which layer of the Earth is composed of nickel and iron (NIFE)?",
        optionA: "Mantle",
        optionB: "Outer Core",
        optionC: "Inner Core",
        correctAnswer: "c",
      },
      {
        question:
          "What is the source of knowledge about the Earth's interior mentioned in the text?",
        optionA: "Solar radiation",
        optionB: "Study of meteoroids",
        optionC: "Study of ocean currents",
        correctAnswer: "b",
      },
      {
        question:
          "What is the primary factor responsible for the formation of igneous rocks?",
        optionA: "Pressure and heat",
        optionB: "Weathering and erosion",
        optionC: "Cooling and solidification of magma",
        correctAnswer: "c",
      },
      {
        question:
          "Which type of rock is formed when igneous rocks are subjected to pressure, heat, and water current?",
        optionA: "Igneous rock",
        optionB: "Sedimentary rock",
        optionC: "Metamorphic rock",
        correctAnswer: "c",
      },
      {
        question:
          "What is the main composition of the continental crust (SIAL)?",
        optionA: "Silica (SI) and Aluminum (AL)",
        optionB: "Silica (SI) and Magnesium (MA)",
        optionC: "Nickel and Iron (NIFE)",
        correctAnswer: "a",
      },
      {
        question: "What forces cause the rock cycle to occur?",
        optionA: "Human activities",
        optionB: "Volcanic eruptions, weathering, and erosion",
        optionC: "Magnetic fields",
        correctAnswer: "b",
      },
      {
        question:
          "What is the primary source of knowledge about the Earth's interior discussed in the text?",
        optionA: "Study of ocean currents",
        optionB: "Seismic waves generated by earthquakes",
        optionC: "Magnetic resonance imaging",
        correctAnswer: "b",
      },
    ],
  };
}

if (localStorage.getItem("activityNumber") == 2) {
  activityData = {
    activity: "Fill in the blanks:",
    questions: [
      {
        question: "The earth's interior study relies on ________ sources.",
        options: ["Direct", "Indirect", "Visible"],
        correctAnswer: "b",
      },
      {
        question:
          "Seismic waves, essential for understanding the earth's interior, are generated by ________.",
        options: ["Volcanoes", "Meteoroids", "Earthquakes"],
        correctAnswer: "c",
      },
      {
        question:
          "The crust is composed of rocks, hard soil, and other materials, and it is also called the ________.",
        options: ["Lithosphere", "Stratosphere", "Troposphere"],
        correctAnswer: "a",
      },
      {
        question:
          "The mantle, located beneath the crust, is primarily made up of ________ and ________.",
        options: ["Silica, Aluminum", "Iron, Magnesium", "Nickel, Iron"],
        correctAnswer: "b",
      },
      {
        question:
          "The inner core's temperature ranges from ________ to ________.",
        options: [
          "900°C to 2,000°C",
          "2,200°C to 5,000°C",
          "3,000°C to 6,000°C",
        ],
        correctAnswer: "b",
      },
      {
        question:
          "Minerals can be identified by their ________, lustre, texture, and hardness.",
        options: ["Weight", "Color", "Density"],
        correctAnswer: "b",
      },
      {
        question:
          "Igneous rocks are formed from the cooling and solidification of ________.",
        options: ["Water", "Lava", "Magma"],
        correctAnswer: "c",
      },
      {
        question:
          "Sedimentary rocks are often formed under ________, resulting in cracks and wave marks.",
        options: ["Fire", "Water", "Wind"],
        correctAnswer: "b",
      },
      {
        question:
          "Metamorphism, causing a change in rocks, involves ________, ________, and ________ currents.",
        options: [
          "Pressure, Wind, Heat",
          "Heat, Water, Ice",
          "Pressure, Heat, Water",
        ],
        correctAnswer: "c",
      },
      {
        question:
          "The rock cycle is set in motion by natural forces like ________, weathering, and erosion.",
        options: [
          "Volcanic eruptions",
          "Tectonic plate movement",
          "Solar radiation",
        ],
        correctAnswer: "a",
      },
    ],
  };
}

if (localStorage.getItem("activityNumber") == 3) {
  activityData = {
    activity: "Write 'True' for True and 'False' for False statements:",
    questions: [
      {
        question: "The earth's interior study relies on direct sources.",
        optionA: "True",
        optionB: "False",
        correctAnswer: "False",
      },
      {
        question:
          "Seismic waves, essential for understanding the earth's interior, are primarily generated by volcanic eruptions.",
        optionA: "True",
        optionB: "False",
        correctAnswer: "False",
      },
      {
        question:
          "The mantle, located beneath the crust, is composed of silica and aluminum.",
        optionA: "True",
        optionB: "False",
        correctAnswer: "False",
      },
      {
        question: "The outer crust is the thickest beneath some mountains.",
        optionA: "True",
        optionB: "False",
        correctAnswer: "True",
      },
      {
        question: "The inner core of the Earth is in a molten state.",
        optionA: "True",
        optionB: "False",
        correctAnswer: "False",
      },
      {
        question:
          "Minerals can be identified by their weight, lustre, texture, and hardness.",
        optionA: "True",
        optionB: "False",
        correctAnswer: "False",
      },
      {
        question:
          "Sedimentary rocks are often formed under the influence of wind, resulting in cracks and wave marks.",
        optionA: "True",
        optionB: "False",
        correctAnswer: "False",
      },
      {
        question:
          "Metamorphism, causing a change in rocks, involves pressure, heat, and water currents.",
        optionA: "True",
        optionB: "False",
        correctAnswer: "True",
      },
      {
        question:
          "Igneous rocks are formed from the cooling and solidification of magma.",
        optionA: "True",
        optionB: "False",
        correctAnswer: "True",
      },
      {
        question:
          "The rock cycle is set in motion by natural forces like volcanic eruptions, weathering, and erosion.",
        optionA: "True",
        optionB: "False",
        correctAnswer: "True",
      },
    ],
  };
}

export var activityData;
